let currentCoin; let priceChart; let selectedRange = '30';
const rangeMap = { '1': '24H', '7': '7D', '30': '30D', '90': '90D', '365': '1Y', max: 'MAX' };
document.addEventListener('DOMContentLoaded', initCoin);
async function initCoin() { const id = new URLSearchParams(location.search).get('id'); if (!id) { setCoinStatus('No coin selected.'); return; } try { currentCoin = await getCoin(id); renderCoin(currentCoin); await loadChart(id, selectedRange); } catch (error) { setCoinStatus(error.message); document.getElementById('coin-detail').innerHTML = `<div class="empty-state">${error.message}<br><a class="back-link" href="index.html">Return to market</a></div>`; } }
function renderCoin(coin) { const market = coin.market_data; document.title = `${coin.name} | The Bull & The Bear`; const change = market.price_change_percentage_24h; document.getElementById('coin-detail').innerHTML = `<div class="coin-head"><div class="coin-title"><img src="${coin.image.large}" alt="${coin.name} logo"><div><h1>${coin.name}</h1><p>${coin.symbol} / #${coin.market_cap_rank || '--'}</p></div></div><div class="coin-price-block"><div class="coin-price">${formatCurrency(market.current_price.usd)}</div><span class="change ${change >= 0 ? 'positive' : 'negative'}">${formatPercent(change)} today</span><br><button class="watch-button ${isFavorite(coin.id) ? 'active' : ''}" id="watch-button" type="button">${isFavorite(coin.id) ? '★ In favorites' : '☆ Add to favorites'}</button></div></div><div class="coin-stats"><div class="coin-stat"><span>Market cap</span><strong>${formatCompact(market.market_cap.usd)}</strong></div><div class="coin-stat"><span>24h volume</span><strong>${formatCompact(market.total_volume.usd)}</strong></div><div class="coin-stat"><span>Market rank</span><strong>#${market.market_cap_rank || '--'}</strong></div><div class="coin-stat"><span>All-time high</span><strong>${formatCurrency(market.ath.usd)}</strong></div><div class="coin-stat"><span>All-time low</span><strong>${formatCurrency(market.atl.usd)}</strong></div></div><div class="chart-panel"><div class="chart-top"><h2>Price history</h2><div class="range-buttons">${Object.entries(rangeMap).map(([value, label]) => `<button class="range-button ${value === selectedRange ? 'active' : ''}" data-days="${value}">${label}</button>`).join('')}</div></div><div class="chart-container"><canvas id="price-chart" aria-label="${coin.name} price history chart"></canvas></div></div>`; document.getElementById('watch-button').addEventListener('click', () => { const added = toggleFavorite({ id: coin.id, name: coin.name, symbol: coin.symbol, image: coin.image.large }); const button = document.getElementById('watch-button'); button.classList.toggle('active', added); button.textContent = added ? '★ In favorites' : '☆ Add to favorites'; showToast(added ? `${coin.name} added to favorites` : `${coin.name} removed from favorites`); }); document.querySelectorAll('.range-button').forEach(button => button.addEventListener('click', async () => { selectedRange = button.dataset.days; document.querySelectorAll('.range-button').forEach(item => item.classList.toggle('active', item === button)); await loadChart(coin.id, selectedRange); })); }
async function loadChart(id, days) { setCoinStatus('Loading price history...'); try { const chart = await getCoinChart(id, days); renderChart(chart); setCoinStatus(''); } catch (error) { setCoinStatus(error.message); } }
function renderChart(data) { const canvas = document.getElementById('price-chart'); if (!canvas) return; if (priceChart) priceChart.destroy(); const styles = getComputedStyle(document.documentElement); const accent = styles.getPropertyValue('--accent').trim(); const muted = styles.getPropertyValue('--muted-text').trim(); const text = styles.getPropertyValue('--text').trim(); priceChart = new Chart(canvas, { type: 'line', data: { labels: data.prices.map(item => new Date(item[0])), datasets: [{ data: data.prices.map(item => item[1]), borderColor: accent, backgroundColor: `${accent}18`, borderWidth: 2, pointRadius: 0, pointHoverRadius: 4, fill: true, tension: .25 }] }, options: { responsive: true, maintainAspectRatio: false, interaction: { intersect: false, mode: 'index' }, plugins: { legend: { display: false }, tooltip: { displayColors: false, callbacks: { label: context => ` ${formatCurrency(context.parsed.y)}` } } }, scales: { x: { type: 'time', time: { unit: daysUnit(selectedRange) }, grid: { display: false }, ticks: { color: muted, maxTicksLimit: 7, font: { family: 'DM Mono', size: 10 } } }, y: { position: 'right', grid: { color: `${muted}22` }, ticks: { color: muted, font: { family: 'DM Mono', size: 10 }, callback: value => formatCurrency(value, true) } } } } }); }
function daysUnit(days) { return days === '1' ? 'hour' : days === 'max' || days === '365' ? 'month' : 'day'; }
function setCoinStatus(message) { const element = document.getElementById('coin-status'); if (element) element.textContent = message; }
document.addEventListener('themechange', () => { if (currentCoin && priceChart) loadChart(currentCoin.id, selectedRange); });
